server:
  port: 18100

spring:
  application:
    name: service-config
security:
  basic:
    enabled: true
  user:
    name: xiaoxian
    password: 123456
        
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      #defaultZone: http://xiaoxian:123456@localhost:18100/eureka/
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000
   